### PR TITLE
restore runnability for pg < 9.4

### PR DESCRIPTION
**Pull request by eschen42**
I was unable to run the image resulting from 
```bash
sudo docker-compose build pg9_3
```
This request has the fixes to support PostgreSQL versions < 9.4 which don't implement

- max_replication_slots in postgresql.conf
- pg_create_physical_replication_slot in the database

### CODE REVIEW

**Comment by tbeadle** [comment]
Thanks so much for the contribution!  I must admit, I don't use postgres < 9.4, so it wasn't tested very thoroughly.

For the Dockerfile changes, I would prefer that update.sh and/or Dockerfile.template are updated.  `update.sh` is used to automatically generate all of the other Dockerfiles.

As for the other change, I think it would be a little more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) as:

```bash
cat >>${PGDATA}/postgresql.conf <<EOF
wal_level = '${WAL_LEVEL}'
max_wal_senders = 2
EOF
if not verlt ${PG_MAJOR} 9.4; then
    echo "max_replication_slots = 2" >> ${PGDATA}/postgresql.conf
fi

**Comment by eschen42** [comment]
That sounds fine, but I see no precedent for calling out behavior for explicit version numbers in `update.sh` - how would you want this to look? E.g., something like this (untested) code snippet:
```bash
if not verlt ${PG_MAJOR} 9.4; then
    sed -i 's/BARMAN_SLOT_NAME=barman//' ${PGDATA}/postgresql.conf
fi
```

**Comment by tbeadle** [comment]
Now that I've thought about it a bit more, rather than modifying the Dockerfile, you could just add a verlt check in image-entrypoint-initdb.d/02_create_replication_slot.sh.  Then you could add an echo statement explaining why the slot is not being created.

**Comment by eschen42** [comment]
Closing - superseded by request #2

**Pull request closed without merging**
